[tool.black]
line-length = 120
skip-string-normalization = true

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gameguard-utils"
version = "0.0.2"
requires-python = ">=3.11"
dependencies = [
    
]
